-- 种子数据：由 backend/scripts/extract_seed.py 从原 DatabaseInitializer.java 生成。
-- 使用 INSERT IGNORE，重复启动不会产生重复数据（依赖各表 UNIQUE 约束）。

-- materials: 145 行
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2001, 'EA888-001', '活塞总成', 'Φ82.5mm EA888 Gen3', '套', 4, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2002, 'EA888-002', '活塞环组', 'Φ82.5mm 三道环', '组', 10, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2003, 'EA888-003', '连杆总成', 'EA888 锻造', '根', 8, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2004, 'EA888-004', '曲轴总成', 'EA888 锻钢', '根', 2, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2005, 'EA888-005', '凸轮轴进气', 'EA888 Gen3 进气', '根', 4, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2006, 'EA888-006', '凸轮轴排气', 'EA888 Gen3 排气', '根', 4, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2007, 'EA888-007', '进气门', 'Φ34mm EA888', '支', 16, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2008, 'EA888-008', '排气门', 'Φ28mm EA888', '支', 16, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2009, 'EA888-009', '气门弹簧', 'EA888 专用', '个', 32, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2010, 'EA888-010', '气缸垫', 'EA888 三层金属', '张', 4, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2011, 'EA888-011', '正时链条', 'EA888 正时链', '根', 4, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2012, 'EA888-012', '正时链条张紧器', 'EA888 液压式', '个', 4, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2013, 'EA888-013', '机油泵总成', 'EA888 可变排量', '台', 2, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2014, 'EA888-014', '水泵总成', 'EA888 电子水泵', '台', 2, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2015, 'EA888-015', '油底壳', 'EA888 铝合金', '个', 2, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2016, 'EA888-016', '气缸盖总成', 'EA888 铝合金', '台', 1, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2017, 'EA888-017', '进气歧管', 'EA888 可变进气', '个', 2, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2018, 'EA888-018', '排气歧管', 'EA888 不锈钢', '个', 2, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2019, 'EA888-019', '涡轮增压器总成', 'EA888 IHI涡轮', '台', 1, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2020, 'EA888-020', '中冷器', 'EA888 风冷式', '个', 1, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2021, 'EA888-021', '高压油泵', 'EA888 直喷', '个', 2, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2022, 'EA888-022', '喷油嘴', 'EA888 6孔直喷', '个', 8, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2023, 'EA888-023', '点火线圈', 'EA888 独立点火', '个', 8, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2024, 'EA888-024', '火花塞', 'EA888 铱金', '个', 16, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2025, 'EA888-025', '发动机控制单元ECU', 'EA888 Bosch MED17', '台', 1, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (2026, 'EA888-026', '机油滤清器', 'EA888 专用', '个', 8, '发动机系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (3001, 'DQ381-001', '离合器片组', 'DQ381 湿式多片', '套', 3, '变速箱系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (3002, 'DQ381-002', '双质量飞轮', 'DQ381 专用', '个', 2, '变速箱系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (3003, 'DQ381-003', '输入轴', 'DQ381 第一轴', '根', 2, '变速箱系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (3004, 'DQ381-004', '输出轴', 'DQ381 第二轴', '根', 2, '变速箱系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (3005, 'DQ381-005', '同步器总成1/2档', 'DQ381 双锥面', '套', 2, '变速箱系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (3006, 'DQ381-006', '同步器总成3/4档', 'DQ381 单锥面', '套', 2, '变速箱系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (3007, 'DQ381-007', '换挡拨叉', 'DQ381 电控液压', '个', 4, '变速箱系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (3008, 'DQ381-008', '变速箱壳体', 'DQ381 铝合金', '个', 1, '变速箱系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (3009, 'DQ381-009', '差速器总成', 'DQ381 前驱', '台', 1, '变速箱系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (3010, 'DQ381-010', '半轴总成左', 'DQ381 前左', '根', 2, '变速箱系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (3011, 'DQ381-011', '半轴总成右', 'DQ381 前右', '根', 2, '变速箱系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (3012, 'DQ381-012', '变速箱油泵', 'DQ381 电动', '台', 2, '变速箱系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (3013, 'DQ381-013', '液力变矩器', 'DQ381 专用', '台', 1, '变速箱系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (3014, 'DQ381-014', '变速箱阀体', 'DQ381 电液控制', '个', 2, '变速箱系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (3015, 'DQ381-015', '变速箱滤清器', 'DQ381 专用', '个', 5, '变速箱系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (3016, 'DQ381-016', '变速箱油底壳', 'DQ381 塑料', '个', 3, '变速箱系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (4001, 'MQB-001', '前减震器总成', 'MQB 麦弗逊', '根', 4, '底盘系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (4002, 'MQB-002', '后减震器总成', 'MQB 多连杆', '根', 4, '底盘系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (4003, 'MQB-003', '前螺旋弹簧', 'MQB 标准型', '根', 4, '底盘系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (4004, 'MQB-004', '后螺旋弹簧', 'MQB 标准型', '根', 4, '底盘系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (4005, 'MQB-005', '前下摆臂总成', 'MQB 冲压焊接', '个', 4, '底盘系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (4006, 'MQB-006', '前上摆臂总成', 'MQB 铝合金', '个', 4, '底盘系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (4007, 'MQB-007', '前横向稳定杆', 'MQB Φ24mm', '根', 2, '底盘系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (4008, 'MQB-008', '后横向稳定杆', 'MQB Φ20mm', '根', 2, '底盘系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (4009, 'MQB-009', '转向节', 'MQB 球墨铸铁', '个', 4, '底盘系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (4010, 'MQB-010', '前轮毂轴承', 'MQB 三代轮毂', '个', 4, '底盘系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (4011, 'MQB-011', '副车架总成', 'MQB 冲压钢板', '台', 1, '底盘系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (4012, 'MQB-012', '后桥总成', 'MQB 多连杆', '台', 1, '底盘系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (4013, 'MQB-013', '后控制臂上', 'MQB 铝合金', '个', 4, '底盘系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (4014, 'MQB-014', '后控制臂下', 'MQB 钢板冲压', '个', 4, '底盘系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (5001, 'BRAKE-001', '前刹车盘', 'Φ312mm 通风盘', '个', 4, '制动系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (5002, 'BRAKE-002', '后刹车盘', 'Φ282mm 实心盘', '个', 4, '制动系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (5003, 'BRAKE-003', '前刹车片套件', '陶瓷配方', '套', 8, '制动系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (5004, 'BRAKE-004', '后刹车片套件', '低金属配方', '套', 8, '制动系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (5005, 'BRAKE-005', '制动总泵', 'MQB 真空助力', '台', 2, '制动系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (5006, 'BRAKE-006', '制动分泵前左', 'MQB 前制动钳', '个', 2, '制动系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (5007, 'BRAKE-007', 'ABS/ESC泵总成', 'Bosch 9.1 ESP', '台', 1, '制动系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (5008, 'BRAKE-008', '制动液壶', 'MQB 专用', '个', 3, '制动系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (5009, 'BRAKE-009', '制动软管前', '加强橡胶', '根', 4, '制动系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (5010, 'BRAKE-010', '电子手刹执行器', 'MQB EPB', '个', 2, '制动系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (6001, 'STEER-001', '电动转向机总成', 'MQB EPS', '台', 1, '转向系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (6002, 'STEER-002', '转向横拉杆', 'MQB 可调式', '根', 4, '转向系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (6003, 'STEER-003', '转向外球头', 'MQB 免维护', '个', 4, '转向系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (6004, 'STEER-004', '转向内球头', 'MQB 专用', '个', 4, '转向系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (6005, 'STEER-005', '转向中间轴', 'MQB 万向节式', '根', 2, '转向系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (6006, 'STEER-006', '方向盘总成', 'MQB 多功能', '个', 1, '转向系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (7001, 'COOL-001', '散热器总成', 'MQB 铝塑', '台', 2, '冷却系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (7002, 'COOL-002', '冷却风扇总成', 'MQB 双风扇', '套', 2, '冷却系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (7003, 'COOL-003', '节温器总成', 'EA888 电子节温器', '个', 3, '冷却系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (7004, 'COOL-004', '冷却液膨胀壶', 'MQB 专用', '个', 3, '冷却系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (7005, 'COOL-005', '冷却液管路套件', 'MQB 硅胶管', '套', 3, '冷却系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (7006, 'COOL-006', '机油冷却器', 'EA888 板式', '个', 2, '冷却系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (8001, 'FUEL-001', '燃油泵总成', 'MQB 内置式', '台', 2, '燃油系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (8002, 'FUEL-002', '燃油滤清器', 'MQB 高压', '个', 8, '燃油系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (8003, 'FUEL-003', '碳罐总成', 'MQB 活性炭', '个', 2, '燃油系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (8004, 'FUEL-004', '燃油箱总成', 'MQB 55L塑料', '个', 1, '燃油系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (8005, 'FUEL-005', '燃油压力调节阀', 'EA888 高压', '个', 2, '燃油系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (9001, 'EXH-001', '三元催化转化器', 'MQB 国六b', '台', 1, '排气系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (9002, 'EXH-002', '前消声器总成', 'MQB 不锈钢', '个', 2, '排气系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (9003, 'EXH-003', '后消声器总成', 'MQB 双出', '个', 2, '排气系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (9004, 'EXH-004', '前排气管', 'MQB 不锈钢', '根', 2, '排气系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (9005, 'EXH-005', '氧传感器前', 'Bosch LSU 4.9', '个', 4, '排气系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (9006, 'EXH-006', '氧传感器后', 'Bosch LSF 4.2', '个', 4, '排气系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1101, 'HVAC-001', '空调压缩机', 'MQB 变排量', '台', 1, '空调系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1102, 'HVAC-002', '冷凝器总成', 'MQB 平行流', '台', 2, '空调系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1103, 'HVAC-003', '蒸发器总成', 'MQB 层叠式', '台', 2, '空调系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1104, 'HVAC-004', '膨胀阀', 'MQB 热力式', '个', 3, '空调系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1105, 'HVAC-005', '鼓风机总成', 'MQB 无刷电机', '台', 2, '空调系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1106, 'HVAC-006', '空调滤芯', 'MQB PM2.5', '个', 10, '空调系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1201, 'BODY-001', '前保险杠总成', 'MQB 注塑', '个', 2, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1202, 'BODY-002', '后保险杠总成', 'MQB 注塑', '个', 2, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1203, 'BODY-003', '前翼子板左', 'MQB 钢板冲压', '个', 2, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1204, 'BODY-004', '前翼子板右', 'MQB 钢板冲压', '个', 2, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1205, 'BODY-005', '发动机盖', 'MQB 铝合金', '个', 1, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1206, 'BODY-006', '行李箱盖', 'MQB 钢板冲压', '个', 1, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1207, 'BODY-007', '前车门总成左', 'MQB 焊接总成', '个', 1, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1208, 'BODY-008', '前车门总成右', 'MQB 焊接总成', '个', 1, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1209, 'BODY-009', '后车门总成左', 'MQB 焊接总成', '个', 1, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1210, 'BODY-010', '后车门总成右', 'MQB 焊接总成', '个', 1, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1211, 'BODY-011', '前挡风玻璃', 'MQB 夹层玻璃', '块', 3, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1212, 'BODY-012', '后挡风玻璃', 'MQB 钢化玻璃', '块', 3, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1213, 'BODY-013', '外后视镜总成左', 'MQB 电动折叠加热', '个', 2, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1214, 'BODY-014', '外后视镜总成右', 'MQB 电动折叠加热', '个', 2, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1215, 'BODY-015', '前大灯总成左', 'MQB LED矩阵', '个', 2, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1216, 'BODY-016', '前大灯总成右', 'MQB LED矩阵', '个', 2, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1217, 'BODY-017', '尾灯总成左', 'MQB LED', '个', 2, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1218, 'BODY-018', '尾灯总成右', 'MQB LED', '个', 2, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1219, 'BODY-019', '散热器格栅', 'MQB 镀铬', '个', 2, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1220, 'BODY-020', '前轮眉内衬', 'MQB 塑料', '个', 4, '车身外饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1301, 'INT-001', '仪表台总成', 'MQB 搪塑', '台', 1, '车身内饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1302, 'INT-002', '组合仪表总成', 'MQB 全液晶', '台', 2, '车身内饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1303, 'INT-003', '前座椅总成左', 'MQB 电动调节加热', '个', 1, '车身内饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1304, 'INT-004', '前座椅总成右', 'MQB 电动调节加热', '个', 1, '车身内饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1305, 'INT-005', '后座椅总成', 'MQB 6/4分折', '套', 1, '车身内饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1306, 'INT-006', '前排安全带', 'MQB 预紧限力', '根', 4, '车身内饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1307, 'INT-007', '门内饰板前左', 'MQB PVC+织物', '个', 2, '车身内饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1308, 'INT-008', '门内饰板前右', 'MQB PVC+织物', '个', 2, '车身内饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1309, 'INT-009', '顶棚总成', 'MQB 无纺布', '个', 1, '车身内饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1310, 'INT-010', '中控台扶手箱', 'MQB 皮革包覆', '个', 2, '车身内饰');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1401, 'ELEC-001', '发电机总成', 'MQB 140A', '台', 1, '电器系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1402, 'ELEC-002', '起动机总成', 'MQB 1.4kW', '台', 1, '电器系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1403, 'ELEC-003', '蓄电池AGM', 'MQB 70Ah AGM', '个', 3, '电器系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1404, 'ELEC-004', '雨刮电机总成', 'MQB 前雨刮', '台', 2, '电器系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1405, 'ELEC-005', '玻璃升降器前左', 'MQB 电动', '个', 2, '电器系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1406, 'ELEC-006', '玻璃升降器前右', 'MQB 电动', '个', 2, '电器系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1407, 'ELEC-007', '中控门锁前左', 'MQB 电控', '个', 3, '电器系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1408, 'ELEC-008', '整车线束总成', 'MQB 主线束', '套', 1, '电器系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1409, 'ELEC-009', '车身控制模块BCM', 'MQB 高配', '台', 1, '电器系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1410, 'ELEC-010', '网关控制单元', 'MQB Gateway', '台', 1, '电器系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1501, 'SAFE-001', '驾驶员安全气囊', 'MQB 单级', '个', 2, '安全系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1502, 'SAFE-002', '副驾驶安全气囊', 'MQB 双级', '个', 2, '安全系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1503, 'SAFE-003', '侧安全气囊左', 'MQB 前排', '个', 2, '安全系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1504, 'SAFE-004', '侧安全气囊右', 'MQB 前排', '个', 2, '安全系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1505, 'SAFE-005', '侧气帘左', 'MQB 贯穿式', '个', 1, '安全系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1506, 'SAFE-006', '侧气帘右', 'MQB 贯穿式', '个', 1, '安全系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1507, 'SAFE-007', '碰撞传感器前', 'MQB 加速度式', '个', 3, '安全系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1508, 'SAFE-008', '胎压传感器', 'MQB 直接式TPMS', '个', 8, '安全系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1509, 'SAFE-009', '安全气囊控制单元', 'MQB ACU', '台', 1, '安全系统');
INSERT IGNORE INTO materials (id,code,name,spec,unit,package_qty,category) VALUES (1510, 'SAFE-010', '倒车雷达探头', 'MQB 超声波', '个', 8, '安全系统');

-- suppliers: 20 行
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1001, 'GYS001', '博世汽车部件(长春)有限公司', '王伟', '0431-88765001', '吉林省长春市汽车经济技术开发区丰采街188号', '吉林', '长春');
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1002, 'GYS002', '大陆汽车电子(长春)有限公司', '李强', '0431-88765002', '吉林省长春市高新技术产业开发区硅谷大街3999号', '吉林', '长春');
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1003, 'GYS003', '采埃孚传动技术(上海)有限公司', '张明', '021-58665003', '上海市嘉定区安亭镇安拓路56号', '上海', '上海');
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1004, 'GYS004', '佛吉亚排气系统(长春)有限公司', '刘洋', '0431-88765004', '吉林省长春市绿园区西新镇开元路99号', '吉林', '长春');
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1005, 'GYS005', '法雷奥汽车电器(武汉)有限公司', '陈亮', '027-87665005', '湖北省武汉市汉南区纱帽街兴城大道388号', '湖北', '武汉');
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1006, 'GYS006', '麦格纳汽车外饰(长春)有限公司', '赵磊', '0431-88765006', '吉林省长春市经济开发区大连路288号', '吉林', '长春');
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1007, 'GYS007', '天合汽车安全系统(上海)有限公司', '孙涛', '021-58665007', '上海市浦东新区康桥工业区康柳路118号', '上海', '上海');
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1008, 'GYS008', '德尔福派克电气系统(长春)有限公司', '周杰', '0431-88765008', '吉林省长春市绿园区西安大路3888号', '吉林', '长春');
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1009, 'GYS009', '海拉车灯(长春)有限公司', '吴刚', '0431-88765009', '吉林省长春市汽车经济技术开发区东风大街999号', '吉林', '长春');
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1010, 'GYS010', '舍弗勒(中国)有限公司', '郑强', '0512-57665010', '江苏省苏州市太仓市宁波东路68号', '江苏', '苏州');
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1011, 'GYS011', '蒂森克虏伯汽车零部件(上海)有限公司', '冯浩', '021-58665011', '上海市奉贤区南桥镇环城北路1288号', '上海', '上海');
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1012, 'GYS012', '伟世通汽车电子(长春)有限公司', '马超', '0431-88765012', '吉林省长春市朝阳区硅谷大街2999号', '吉林', '长春');
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1013, 'GYS013', '李尔汽车座椅(长春)有限公司', '宋博', '0431-88765013', '吉林省长春市高新技术产业开发区光谷大街3888号', '吉林', '长春');
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1014, 'GYS014', '博格华纳传动系统(大连)有限公司', '韩磊', '0411-87665014', '辽宁省大连市金州区经济技术开发区淮河中路88号', '辽宁', '大连');
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1015, 'GYS015', '马勒发动机零部件(上海)有限公司', '林峰', '021-58665015', '上海市嘉定区徐行镇徐潘路258号', '上海', '上海');
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1016, 'GYS016', '康明斯涡轮增压技术(无锡)有限公司', '唐辉', '0510-85665016', '江苏省无锡市新区长江路28号', '江苏', '无锡');
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1017, 'GYS017', '均胜汽车安全系统(宁波)有限公司', '方明', '0574-87665017', '浙江省宁波市鄞州区潘火街道下应北路789号', '浙江', '宁波');
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1018, 'GYS018', '福耀玻璃工业集团(长春)有限公司', '曹征', '0431-88765018', '吉林省长春市经济开发区世纪大街1666号', '吉林', '长春');
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1019, 'GYS019', '万向钱潮传动轴(杭州)有限公司', '沈建', '0571-87665019', '浙江省杭州市萧山区万向路1号', '浙江', '杭州');
INSERT IGNORE INTO suppliers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (1020, 'GYS020', '华域汽车系统(上海)有限公司', '蒋鹏', '021-58665020', '上海市嘉定区安亭镇曹安路5588号', '上海', '上海');

-- customers: 20 行
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3001, 'KH001', '一汽大众销售有限责任公司', '赵总经理', '0431-85908888', '吉林省长春市汽车经济技术开发区东风大街1999号', '吉林', '长春');
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3002, 'KH002', '长春通立汽车销售服务有限公司', '钱经理', '0431-84626888', '吉林省长春市绿园区正阳街4288号', '吉林', '长春');
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3003, 'KH003', '北京中润发汽车销售有限公司', '孙经理', '010-67889888', '北京市朝阳区北苑路168号', '北京', '北京');
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3004, 'KH004', '上海永达汽车销售服务有限公司', '李经理', '021-58559888', '上海市浦东新区张杨路2758号', '上海', '上海');
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3005, 'KH005', '广州大吉汽车销售服务有限公司', '周经理', '020-87239888', '广东省广州市白云区白云大道北1375号', '广东', '广州');
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3006, 'KH006', '成都新双立汽车销售服务有限公司', '吴经理', '028-85129888', '四川省成都市武侯区机场路68号', '四川', '成都');
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3007, 'KH007', '深圳昊天林汽车销售服务有限公司', '郑经理', '0755-83709888', '广东省深圳市福田区香蜜湖路6028号', '广东', '深圳');
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3008, 'KH008', '武汉恒信汽车销售服务有限公司', '王经理', '027-84897888', '湖北省武汉市汉阳区龙阳大道86号', '湖北', '武汉');
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3009, 'KH009', '杭州百得利汽车销售服务有限公司', '冯经理', '0571-88997888', '浙江省杭州市拱墅区石祥路471号', '浙江', '杭州');
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3010, 'KH010', '南京协众汽车销售服务有限公司', '陈经理', '025-85869888', '江苏省南京市江宁区天元东路228号', '江苏', '南京');
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3011, 'KH011', '郑州威佳汽车销售服务有限公司', '褚经理', '0371-65667888', '河南省郑州市金水区花园路北段88号', '河南', '郑州');
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3012, 'KH012', '天津捷通汽车销售服务有限公司', '卫经理', '022-84997888', '天津市西青区中北镇汽车园南路8号', '天津', '天津');
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3013, 'KH013', '重庆商社汽车销售服务有限公司', '蒋经理', '023-68892888', '重庆市渝北区龙溪街道红锦大道566号', '重庆', '重庆');
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3014, 'KH014', '西安新丰泰汽车销售服务有限公司', '沈经理', '029-86269888', '陕西省西安市未央区明光路98号', '陕西', '西安');
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3015, 'KH015', '济南庞大汽车销售服务有限公司', '韩经理', '0531-87509888', '山东省济南市槐荫区经十西路3888号', '山东', '济南');
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3016, 'KH016', '哈尔滨龙海汽车销售服务有限公司', '杨经理', '0451-86809888', '黑龙江省哈尔滨市道里区机场路18号', '黑龙江', '哈尔滨');
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3017, 'KH017', '沈阳和泰汽车销售服务有限公司', '朱经理', '024-86509888', '辽宁省沈阳市铁西区北二中路33号', '辽宁', '沈阳');
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3018, 'KH018', '长沙华洋汽车销售服务有限公司', '秦经理', '0731-82809888', '湖南省长沙市岳麓区麓谷大道668号', '湖南', '长沙');
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3019, 'KH019', '合肥宝荣汽车销售服务有限公司', '尤经理', '0551-63669888', '安徽省合肥市包河区繁华大道288号', '安徽', '合肥');
INSERT IGNORE INTO customers (id,code,name,contact_name,contact_phone,address,province,city) VALUES (3020, 'KH020', '福州永达汽车销售服务有限公司', '许经理', '0591-83509888', '福建省福州市仓山区福峡路88号', '福建', '福州');

-- warehouses: 10 行
INSERT IGNORE INTO warehouses (id,code,name,address,city,type) VALUES (4001, 'CK001', '长春一厂总装仓库', '吉林省长春市汽车经济技术开发区东风大街1号', '长春', '总装仓库');
INSERT IGNORE INTO warehouses (id,code,name,address,city,type) VALUES (4002, 'CK002', '长春二厂总装仓库', '吉林省长春市绿园区西新经济技术开发区', '长春', '总装仓库');
INSERT IGNORE INTO warehouses (id,code,name,address,city,type) VALUES (4003, 'CK003', '长春发动机工厂仓库', '吉林省长春市汽车经济技术开发区大众路888号', '长春', '发动机仓库');
INSERT IGNORE INTO warehouses (id,code,name,address,city,type) VALUES (4004, 'CK004', '长春传动器工厂仓库', '吉林省长春市绿园区长白公路18号', '长春', '传动器仓库');
INSERT IGNORE INTO warehouses (id,code,name,address,city,type) VALUES (4005, 'CK005', '成都工厂总装仓库', '四川省成都市龙泉驿区车城东七路368号', '成都', '总装仓库');
INSERT IGNORE INTO warehouses (id,code,name,address,city,type) VALUES (4006, 'CK006', '佛山工厂总装仓库', '广东省佛山市南海区狮山镇虹岭路1号', '佛山', '总装仓库');
INSERT IGNORE INTO warehouses (id,code,name,address,city,type) VALUES (4007, 'CK007', '天津工厂总装仓库', '天津市滨海新区经济技术开发区泰达大街88号', '天津', '总装仓库');
INSERT IGNORE INTO warehouses (id,code,name,address,city,type) VALUES (4008, 'CK008', '青岛工厂总装仓库', '山东省青岛市即墨区汽车产业新城大众一路1号', '青岛', '总装仓库');
INSERT IGNORE INTO warehouses (id,code,name,address,city,type) VALUES (4009, 'CK009', '长春冲压中心仓库', '吉林省长春市汽车经济技术开发区富奥路666号', '长春', '冲压仓库');
INSERT IGNORE INTO warehouses (id,code,name,address,city,type) VALUES (4010, 'CK010', '长春备件中心仓库', '吉林省长春市宽城区北环城路2888号', '长春', '备件仓库');

-- locations: 30 行
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5001, 4001, 'KW-1A-A01', 'A区01库位', 'A', 01, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5002, 4001, 'KW-1A-A02', 'A区02库位', 'A', 01, 2);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5003, 4001, 'KW-1A-A03', 'A区03库位', 'A', 02, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5004, 4001, 'KW-1A-B01', 'B区01库位', 'B', 01, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5005, 4001, 'KW-1A-B02', 'B区02库位', 'B', 01, 2);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5006, 4001, 'KW-1A-C01', 'C区01库位', 'C', 01, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5007, 4002, 'KW-2A-A01', 'A区01库位', 'A', 01, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5008, 4002, 'KW-2A-A02', 'A区02库位', 'A', 01, 2);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5009, 4002, 'KW-2A-B01', 'B区01库位', 'B', 01, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5010, 4002, 'KW-2A-B02', 'B区02库位', 'B', 01, 2);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5011, 4003, 'KW-FDJ-A01', '发动机A区01库位', 'A', 01, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5012, 4003, 'KW-FDJ-A02', '发动机A区02库位', 'A', 01, 2);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5013, 4003, 'KW-FDJ-B01', '发动机B区01库位', 'B', 02, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5014, 4004, 'KW-CDQ-A01', '传动器A区01库位', 'A', 01, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5015, 4004, 'KW-CDQ-A02', '传动器A区02库位', 'A', 01, 2);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5016, 4005, 'KW-CDA-A01', '成都A区01库位', 'A', 01, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5017, 4005, 'KW-CDA-A02', '成都A区02库位', 'A', 01, 2);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5018, 4005, 'KW-CDA-B01', '成都B区01库位', 'B', 02, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5019, 4006, 'KW-FSA-A01', '佛山A区01库位', 'A', 01, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5020, 4006, 'KW-FSA-B01', '佛山B区01库位', 'B', 02, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5021, 4007, 'KW-TJA-A01', '天津A区01库位', 'A', 01, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5022, 4007, 'KW-TJA-B01', '天津B区01库位', 'B', 02, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5023, 4008, 'KW-QDA-A01', '青岛A区01库位', 'A', 01, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5024, 4008, 'KW-QDA-B01', '青岛B区01库位', 'B', 02, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5025, 4009, 'KW-CYA-A01', '冲压A区01库位', 'A', 01, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5026, 4009, 'KW-CYA-B01', '冲压B区01库位', 'B', 02, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5027, 4010, 'KW-BJA-A01', '备件A区01库位', 'A', 01, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5028, 4010, 'KW-BJA-A02', '备件A区02库位', 'A', 01, 2);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5029, 4010, 'KW-BJA-B01', '备件B区01库位', 'B', 02, 1);
INSERT IGNORE INTO locations (id,warehouse_id,code,name,area,shelf,layer) VALUES (5030, 4010, 'KW-BJA-C01', '备件C区01库位', 'C', 03, 1);

-- users: 3 行
INSERT IGNORE INTO users (username,password,nickname,role) VALUES ('admin', '123456', '系统管理员', 'admin');
INSERT IGNORE INTO users (username,password,nickname,role) VALUES ('zhangsan', '123456', '张三', 'operator');
INSERT IGNORE INTO users (username,password,nickname,role) VALUES ('lisi', '123456', '李四', 'operator');
